# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d0affcc265155855bc32cd71c059e65cf2e74b591746d72dac1fb8bcc186ddd8e7a5ef109b52016a2c75d375ab232bc48b62f67dbf04ff3502f0ca6ac095875

test:
  secret_key_base: ea0005c01f42f57b58d0068d9d61c58928c59c5e4e611570a1ee8cf36361300a766d7d8fb8b74cf1f6e69bbd0e3bfaa817ecb60b76a6543e65584a71ddef1f17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
